apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "kubernetes.io/os"
      operator: In
      values: ["linux"]
  limits:
    resources:
      cpu: "1000"
  provider:
    subnetSelector:
      karpenter.sh/discovery: aks-cluster
    securityGroupSelector:
      karpenter.sh/discovery: aks-cluster
  ttlSecondsAfterEmpty: 30
